### ISSUE TITLE
ModuleNotFoundError: No module named 'easymocap'

### ISSUE THREAD

**Issue by anilesec** [dihuangdh/HHOR#3]
Hi @dihuangdh 

I am trying to run the demo you provided

When I run "sh apps/3_background_matting.sh", I get "easymocap" missing error

More information below:
python tools/preprocess_mask.py /scratch/2/user/aswamy/projects/hhor_evaluation/HHOR/data/DEMO_OUT/3_Giuliano
Traceback (most recent call last):
  File "tools/preprocess_mask.py", line 14, in <module>
    from easymocap.mytools.camera_utils import read_camera
ModuleNotFoundError: No module named 'easymocap'

**Comment by dihuangdh** [comment]
Hi @anilesec ,

The easymocap part has not been released yet. 

It seems that besides the hand tracking module, some other modules also depend on easymocap. I will upload some easymocap functions and fix your problem tomorrow.

**Comment by anilesec** [comment]
Thanks @dihuangdh 

Yes, all steps from step3 are dependent on easymocap. I would be keenly waiting to run this demo as i have planned to test your impressive and cool method on more captured sequences.

Thanks in advance!

**Comment by dihuangdh** [comment]
Hi @anilesec ,

I checked all the easymocap dependencies in the current library, it only uses two functions of easymocap: `easymocap.mytools` and `easymocap.smplmodel`.

Both of them can be fulfilled by installing the public version of [EasyMocap](https://github.com/zju3dv/EasyMocap).

**Comment by anilesec** [comment]
Thank  you @dihuangdh 
I installed Easymocap and managed to run steps 3, 4, and 5. However,  I get the following error when I run "Dense reconstruction"

Command:
<< CUDA_VISIBLE_DEVICES=0 python exp_runner.py --mode train --conf ./confs/demo/hand_scanner_wmask_wbarf_wsem_warp10.0_mask5_demo.conf --case demo >>

Error:

Traceback (most recent call last):
  File "exp_runner.py", line 594, in <module>
    runner = Runner(args.conf, args.mode, args.case, args.is_continue)
  File "exp_runner.py", line 57, in __init__
    self.dataset = Dataset(self.conf['dataset'])
  File "/scratch/2/user/aswamy/projects/hhor_evaluation/HHOR/NeuS/models/dataset.py", line 64, in __init__
    camdata = read_cameras_binary(os.path.join(self.data_dir, 'colmap', 'cameras.bin'))
  File "/scratch/2/user/aswamy/projects/hhor_evaluation/HHOR/NeuS/models/colmap_utils.py", line 115, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: **'/scratch/2/user/aswamy/projects/hhor_evaluation/HHOR/data/DEMO/3_Giuliano/colmap/cameras.bin'**

**Comment by anilesec** [comment]
Thanks @dihuangdh for a suggested workaround. It works! Training is going on for the demo video.

However, as I mentioned before I would like to test this method on the captured video. Therefore, is it possible to provide the missing part(Hand tracking code)? If its not possible to release it officially, could you please release it unofficially, just for testing purposes? Thank you!

**Comment by dihuangdh** [comment]
Hi, @anilesec we wish to release the hand-tracking part as soon as possible. Unfortunately, since the private version of EasyMocap is related to some commercial usage, there is still some work to do for releasing the next public version of EasyMocap. Stay tuned, we hope it can be done this month or next month.

**Comment by redgreenblue3** [comment]
Hi, thanks a lot for the cool project! What's the status on releasing the hand-tracking code? 

I would like to use your method in my own research project, but as far as I can tell, without the hand-tracking code, it's currently not possible to use this method on own data and therefore it can't be used for downstream applications / research. This is a pity in my opinion.

Looking forward to your response and again thanks a lot for your contribution to the community.

**Comment by dihuangdh** [comment]
Thanks for your interest in our project. @redgreenblue3 

The code will be released no late than Jun 18. Qing and I are working on it. 

I am so sorry for the delay of the hand-tracking code release.

**Comment by dihuangdh** [comment]
The hand tracking code is released here: https://chingswy.github.io/easymocap-public-doc/develop/03_fitsmpl_monocular.html#fit-mano-to-fixed-hand-pose

**Comment by redgreenblue3** [comment]
Thank you so much, that's awesome! It really goes a long way.
